FROM quay.io/centos/centos:stream9

RUN dnf install \
        systemd-udev NetworkManager nftables vim net-tools \
        wireguard-tools libreswan NetworkManager-libreswan git \
        dnsmasq wget tcpdump iproute procps-ng nispor nmstate -y && \
    dnf clean all

RUN find /etc/NetworkManager/system-connections/ -type f -exec rm -v {} \;

RUN systemctl enable systemd-udevd && systemctl disable NetworkManager

CMD ["/usr/sbin/init"]
