FROM quay.io/centos/centos:stream10

RUN dnf install -y \
        systemd-udev NetworkManager nftables vim net-tools \
        wireguard-tools libreswan NetworkManager-libreswan git \
        dnsmasq wget tcpdump iproute procps-ng nmstate python3-libnmstate && \
    dnf clean all

RUN find /etc/NetworkManager/system-connections/ -type f -exec rm {} \;

RUN systemctl enable systemd-udevd && systemctl disable NetworkManager

CMD ["/usr/sbin/init"]
