interface=802_1x_srv
driver=wired
debug=2
ieee8021x=1
eap_reauth_period=3600
eap_server=1
use_pae_group_addr=1
eap_user_file=/etc/hostapd/hostapd.eap_user
ca_cert=/etc/hostapd/ca.crt
dh_file=/etc/hostapd/dh.pem
server_cert=/etc/hostapd/ieee802-1x-srv.example.org.crt
private_key=/etc/hostapd/ieee802-1x-srv.example.org.key
private_key_passwd=serverpass
logger_syslog=-1
logger_syslog_level=0
